// <auto-generated />
using System;
using Lappy.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lappy.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316081207_addedProducts")]
    partial class addedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lappy.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Productivity"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("Lappy.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Lappy.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Lappy.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("PaymentDueDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Lappy.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpuModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphicsCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardDiskSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("ListPrice10")
                        .HasColumnType("float");

                    b.Property<double>("ListPrice100")
                        .HasColumnType("float");

                    b.Property<double>("ListPrice25")
                        .HasColumnType("float");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RamMemory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "ASUS",
                            CategoryId = 2,
                            Colour = "Quiet Blue",
                            CpuModel = "Core i3",
                            Description = "<h4>Effortless Performance. Vibrant Visuals.</h4><p>The <strong>ASUS Vivobook 15</strong> is your everyday companion that’s always ready to make light work of your agenda.</p><ul><li><strong>NanoEdge Display:</strong> Immersive viewing.</li><li><strong>ErgoSense Keyboard:</strong> Optimum key bounce.</li></ul>",
                            GraphicsCard = "Integrated Intel UHD",
                            HardDiskSize = "512 GB",
                            ListPrice = 40990.0,
                            ListPrice10 = 39000.0,
                            ListPrice100 = 35000.0,
                            ListPrice25 = 37000.0,
                            ModelName = "Vivobook 15",
                            OS = "Windows 11 Home",
                            RamMemory = "8 GB",
                            ScreenSize = "15.6 Inches",
                            SpecialFeatures = "Backlit Keyboard, Anti Glare Coating"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            CategoryId = 2,
                            Colour = "Midnight",
                            CpuModel = "M3 Chip",
                            Description = "<h4>Lean. Mean. M3 Machine.</h4><p>The <strong>MacBook Air</strong> sails through work and play with the M3 chip.</p><ul><li><strong>Up to 18 Hours Battery:</strong> Go all day.</li><li><strong>MagSafe:</strong> Easy magnetic charging.</li></ul>",
                            GraphicsCard = "8-core GPU",
                            HardDiskSize = "256 GB",
                            ListPrice = 114900.0,
                            ListPrice10 = 110000.0,
                            ListPrice100 = 100000.0,
                            ListPrice25 = 105000.0,
                            ModelName = "MacBook Air M3",
                            OS = "macOS",
                            RamMemory = "8 GB",
                            ScreenSize = "13.6 Inches",
                            SpecialFeatures = "Liquid Retina Display, Silent Design"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Samsung",
                            CategoryId = 2,
                            Colour = "Graphite",
                            CpuModel = "Core i7",
                            Description = "<h4>Thin, Light, and Premium AMOLED.</h4><p>Elevate your work with the stunning 3K resolution display.</p><ul><li><strong>Dynamic AMOLED 2X:</strong> 120Hz refresh rate.</li><li><strong>Galaxy Ecosystem:</strong> Seamless file movement.</li></ul>",
                            GraphicsCard = "Intel Iris Xe",
                            HardDiskSize = "512 GB",
                            ListPrice = 135000.0,
                            ListPrice10 = 130000.0,
                            ListPrice100 = 120000.0,
                            ListPrice25 = 125000.0,
                            ModelName = "Galaxy Book3 Pro",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "14 Inches",
                            SpecialFeatures = "3K AMOLED Display"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "LG",
                            CategoryId = 2,
                            Colour = "Black",
                            CpuModel = "Core i7",
                            Description = "<h4>Huge Screen. Featherweight Feel.</h4><p>The <strong>LG Gram 17</strong> offers a massive display in a feather-light body.</p><ul><li><strong>WQXGA:</strong> High resolution 16:10 display.</li><li><strong>Military Grade:</strong> Passed MIL-STD-810G tests.</li></ul>",
                            GraphicsCard = "Intel Iris Xe",
                            HardDiskSize = "1 TB",
                            ListPrice = 145000.0,
                            ListPrice10 = 140000.0,
                            ListPrice100 = 130000.0,
                            ListPrice25 = 135000.0,
                            ModelName = "Gram 17",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "17 Inches",
                            SpecialFeatures = "Ultra Lightweight"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Acer",
                            CategoryId = 2,
                            Colour = "Silver",
                            CpuModel = "Ryzen 5",
                            Description = "<h4>The AI-Ready Powerhouse.</h4><p>An easy-to-carry OLED laptop for the modern multitasker.</p><ul><li><strong>OLED Brilliance:</strong> 100% DCI-P3 color gamut.</li><li><strong>TwinAir:</strong> Efficient dual fan cooling.</li></ul>",
                            GraphicsCard = "Radeon Graphics",
                            HardDiskSize = "512 GB",
                            ListPrice = 65000.0,
                            ListPrice10 = 62000.0,
                            ListPrice100 = 58000.0,
                            ListPrice25 = 60000.0,
                            ModelName = "Swift Go 14",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "14 Inches",
                            SpecialFeatures = "OLED Display"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "HP",
                            CategoryId = 2,
                            Colour = "Silver",
                            CpuModel = "Core i5",
                            Description = "<h4>Work Hard. Play Harder.</h4><p>Stunning screen and powerful processor for an all-round experience.</p><ul><li><strong>Eyesafe:</strong> Reduces blue light.</li><li><strong>Fast Charge:</strong> 0 to 50% in 30 mins.</li></ul>",
                            GraphicsCard = "Intel Iris Xe",
                            HardDiskSize = "512 GB",
                            ListPrice = 72000.0,
                            ListPrice10 = 70000.0,
                            ListPrice100 = 65000.0,
                            ListPrice25 = 68000.0,
                            ModelName = "Pavilion Plus 14",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "14 Inches",
                            SpecialFeatures = "5MP Camera"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "ASUS",
                            CategoryId = 2,
                            Colour = "Ponder Blue",
                            CpuModel = "Core i7",
                            Description = "<h4>Power and Elegance.</h4><p>Thin, light, and powerful with a timeless design.</p><ul><li><strong>Harman Kardon:</strong> Unrivaled sound.</li><li><strong>NumberPad 2.0:</strong> LED keypad in touchpad.</li></ul>",
                            GraphicsCard = "Intel Iris Xe",
                            HardDiskSize = "1 TB",
                            ListPrice = 98000.0,
                            ListPrice10 = 95000.0,
                            ListPrice100 = 89000.0,
                            ListPrice25 = 92000.0,
                            ModelName = "Zenbook 14 OLED",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "14 Inches",
                            SpecialFeatures = "90Hz OLED"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "HP",
                            CategoryId = 1,
                            Colour = "Performance Blue",
                            CpuModel = "Ryzen 5",
                            Description = "<h4>Desktop Power to Go.</h4><p>Keep up with the biggest games with the HP Victus 15.</p><ul><li><strong>144Hz Screen:</strong> Crisp gameplay.</li><li><strong>OMEN Hub:</strong> Elevate your play.</li></ul>",
                            GraphicsCard = "NVIDIA RTX 3050",
                            HardDiskSize = "512 GB",
                            ListPrice = 75000.0,
                            ListPrice10 = 72000.0,
                            ListPrice100 = 68000.0,
                            ListPrice25 = 70000.0,
                            ModelName = "Victus 15",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "15.6 Inches",
                            SpecialFeatures = "Fast Charging"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Lenovo",
                            CategoryId = 1,
                            Colour = "Storm Grey",
                            CpuModel = "Ryzen 7",
                            Description = "<h4>Smart Gaming.</h4><p>Sleek look without sacrificing raw power.</p><ul><li><strong>AI Engine+:</strong> Automatically boosts FPS.</li><li><strong>ColdFront 5.0:</strong> Advanced thermals.</li></ul>",
                            GraphicsCard = "NVIDIA RTX 4060",
                            HardDiskSize = "1 TB",
                            ListPrice = 135000.0,
                            ListPrice10 = 130000.0,
                            ListPrice100 = 120000.0,
                            ListPrice25 = 125000.0,
                            ModelName = "Legion Slim 5",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "16 Inches",
                            SpecialFeatures = "AI Engine+"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "MSI",
                            CategoryId = 1,
                            Colour = "Black",
                            CpuModel = "Core i7",
                            Description = "<h4>Sharpen Your Game.</h4><p>Forged for greatness in the virtual battlefield.</p><ul><li><strong>4-Zone RGB:</strong> Custom lighting style.</li><li><strong>Cooler Boost 5:</strong> Dedicated cooling.</li></ul>",
                            GraphicsCard = "NVIDIA RTX 4050",
                            HardDiskSize = "1 TB",
                            ListPrice = 95000.0,
                            ListPrice10 = 92000.0,
                            ListPrice100 = 88000.0,
                            ListPrice25 = 90000.0,
                            ModelName = "Katana 15",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "15.6 Inches",
                            SpecialFeatures = "4-Zone RGB"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Razer",
                            CategoryId = 1,
                            Colour = "Black",
                            CpuModel = "Core i9",
                            Description = "<h4>More Pixels.</h4><p>Premium experience with unmatched build quality.</p><ul><li><strong>Mini-LED:</strong> Toggle between 4K and FHD+.</li><li><strong>Vapor Chamber:</strong> Extreme cooling.</li></ul>",
                            GraphicsCard = "NVIDIA RTX 4080",
                            HardDiskSize = "1 TB",
                            ListPrice = 350000.0,
                            ListPrice10 = 340000.0,
                            ListPrice100 = 320000.0,
                            ListPrice25 = 330000.0,
                            ModelName = "Blade 16",
                            OS = "Windows 11",
                            RamMemory = "32 GB",
                            ScreenSize = "16 Inches",
                            SpecialFeatures = "Dual Mode Mini-LED"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Acer",
                            CategoryId = 1,
                            Colour = "Black",
                            CpuModel = "Core i5",
                            Description = "<h4>Gateway to Gaming.</h4><p>The perfect entry into the world of PC gaming.</p><ul><li><strong>NitroSense:</strong> Control fan speeds easily.</li><li><strong>DTS:X:</strong> 3D spatial sound.</li></ul>",
                            GraphicsCard = "NVIDIA RTX 2050",
                            HardDiskSize = "512 GB",
                            ListPrice = 58000.0,
                            ListPrice10 = 55000.0,
                            ListPrice100 = 50000.0,
                            ListPrice25 = 53000.0,
                            ModelName = "Nitro V 15",
                            OS = "Windows 11",
                            RamMemory = "8 GB",
                            ScreenSize = "15.6 Inches",
                            SpecialFeatures = "Dual Fan Cooling"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Alienware",
                            CategoryId = 1,
                            Colour = "Dark Metallic Moon",
                            CpuModel = "Core i9",
                            Description = "<h4>Ultimate Dominance.</h4><p>Desktop replacement designed for the serious gamer.</p><ul><li><strong>Cryo-Tech:</strong> Peak performance interface.</li><li><strong>18-inch Display:</strong> Total immersion.</li></ul>",
                            GraphicsCard = "NVIDIA RTX 4090",
                            HardDiskSize = "2 TB",
                            ListPrice = 450000.0,
                            ListPrice10 = 440000.0,
                            ListPrice100 = 420000.0,
                            ListPrice25 = 430000.0,
                            ModelName = "m18 R1",
                            OS = "Windows 11",
                            RamMemory = "64 GB",
                            ScreenSize = "18 Inches",
                            SpecialFeatures = "CherryMX Mechanical Keys"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Gigabyte",
                            CategoryId = 1,
                            Colour = "Black",
                            CpuModel = "Core i7",
                            Description = "<h4>Engineered to Win.</h4><p>High performance refined for competitive shooters.</p><ul><li><strong>Windforce:</strong> Silent and cool.</li><li><strong>AI Power:</strong> Dynamic allocation.</li></ul>",
                            GraphicsCard = "NVIDIA RTX 4060",
                            HardDiskSize = "1 TB",
                            ListPrice = 120000.0,
                            ListPrice10 = 115000.0,
                            ListPrice100 = 105000.0,
                            ListPrice25 = 110000.0,
                            ModelName = "AORUS 15",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "15.6 Inches",
                            SpecialFeatures = "240Hz Screen"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Dell",
                            CategoryId = 3,
                            Colour = "Platinum Silver",
                            CpuModel = "Core i9",
                            Description = "<h4>Creative Vision.</h4><p>The gold standard for Windows premium laptops.</p><ul><li><strong>4-Sided InfinityEdge:</strong> Stunning views.</li><li><strong>Waves Nx:</strong> Studio sound.</li></ul>",
                            GraphicsCard = "NVIDIA RTX 4050",
                            HardDiskSize = "1 TB",
                            ListPrice = 245000.0,
                            ListPrice10 = 240000.0,
                            ListPrice100 = 230000.0,
                            ListPrice25 = 235000.0,
                            ModelName = "XPS 15",
                            OS = "Windows 11 Pro",
                            RamMemory = "32 GB",
                            ScreenSize = "15.6 Inches",
                            SpecialFeatures = "InfinityEdge Touch"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Lenovo",
                            CategoryId = 3,
                            Colour = "Black",
                            CpuModel = "Core i7 vPro",
                            Description = "<h4>Business Benchmark.</h4><p>Legendary reliability in an ultra-light carbon fiber body.</p><ul><li><strong>PrivacyGuard:</strong> Security for your screen.</li><li><strong>Pro Security:</strong> vPro management.</li></ul>",
                            GraphicsCard = "Integrated Intel UHD",
                            HardDiskSize = "512 GB",
                            ListPrice = 185000.0,
                            ListPrice10 = 180000.0,
                            ListPrice100 = 170000.0,
                            ListPrice25 = 175000.0,
                            ModelName = "ThinkPad X1 Carbon",
                            OS = "Windows 11 Pro",
                            RamMemory = "16 GB",
                            ScreenSize = "14 Inches",
                            SpecialFeatures = "Carbon Fiber Build"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Microsoft",
                            CategoryId = 3,
                            Colour = "Sandstone",
                            CpuModel = "Core i5",
                            Description = "<h4>Style and Speed.</h4><p>Sleek, elegant, and perfectly integrated touch experience.</p><ul><li><strong>PixelSense:</strong> High-res touch.</li><li><strong>Alcantara:</strong> Premium comfort.</li></ul>",
                            GraphicsCard = "Integrated Intel Iris Xe",
                            HardDiskSize = "512 GB",
                            ListPrice = 105000.0,
                            ListPrice10 = 100000.0,
                            ListPrice100 = 90000.0,
                            ListPrice25 = 95000.0,
                            ModelName = "Surface Laptop 5",
                            OS = "Windows 11",
                            RamMemory = "8 GB",
                            ScreenSize = "13.5 Inches",
                            SpecialFeatures = "Alcantara Palm Rest"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "HP",
                            CategoryId = 3,
                            Colour = "Nightfall Black",
                            CpuModel = "Core i7",
                            Description = "<h4>Adapts to You.</h4><p>Beautiful gem-cut design that works as a tablet or laptop.</p><ul><li><strong>Stylus Included:</strong> For creative work.</li><li><strong>GlamCam:</strong> 5MP clarity.</li></ul>",
                            GraphicsCard = "Integrated Intel Iris Xe",
                            HardDiskSize = "1 TB",
                            ListPrice = 165000.0,
                            ListPrice10 = 160000.0,
                            ListPrice100 = 150000.0,
                            ListPrice25 = 155000.0,
                            ModelName = "Spectre x360",
                            OS = "Windows 11",
                            RamMemory = "16 GB",
                            ScreenSize = "13.5 Inches",
                            SpecialFeatures = "2-in-1 Flip, Stylus"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Dell",
                            CategoryId = 3,
                            Colour = "Grey",
                            CpuModel = "Core i5",
                            Description = "<h4>Smart Collaboration.</h4><p>The smallest and most intelligent premium business laptop.</p><ul><li><strong>ExpressConnect:</strong> Best network join.</li><li><strong>Intelligent Audio:</strong> Noise cancellation.</li></ul>",
                            GraphicsCard = "Integrated Intel UHD",
                            HardDiskSize = "512 GB",
                            ListPrice = 115000.0,
                            ListPrice10 = 110000.0,
                            ListPrice100 = 100000.0,
                            ListPrice25 = 105000.0,
                            ModelName = "Latitude 7440",
                            OS = "Windows 11 Pro",
                            RamMemory = "16 GB",
                            ScreenSize = "14 Inches",
                            SpecialFeatures = "Privacy Shutter"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Apple",
                            CategoryId = 3,
                            Colour = "Space Black",
                            CpuModel = "M3 Pro Chip",
                            Description = "<h4>Pro Power.</h4><p>Extreme dynamic range and pro performance for creators.</p><ul><li><strong>XDR Display:</strong> 1,000,000:1 contrast.</li><li><strong>ProMotion:</strong> 120Hz fluid motion.</li></ul>",
                            GraphicsCard = "14-core GPU",
                            HardDiskSize = "512 GB",
                            ListPrice = 199900.0,
                            ListPrice10 = 195000.0,
                            ListPrice100 = 185000.0,
                            ListPrice25 = 190000.0,
                            ModelName = "MacBook Pro 14",
                            OS = "macOS",
                            RamMemory = "18 GB",
                            ScreenSize = "14.2 Inches",
                            SpecialFeatures = "ProMotion 120Hz"
                        });
                });

            modelBuilder.Entity("Lappy.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Lappy.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Lappy.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Lappy.Models.OrderDetail", b =>
                {
                    b.HasOne("Lappy.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lappy.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lappy.Models.OrderHeader", b =>
                {
                    b.HasOne("Lappy.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Lappy.Models.Product", b =>
                {
                    b.HasOne("Lappy.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lappy.Models.ProductImage", b =>
                {
                    b.HasOne("Lappy.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lappy.Models.ShoppingCart", b =>
                {
                    b.HasOne("Lappy.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lappy.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lappy.Models.ApplicationUser", b =>
                {
                    b.HasOne("Lappy.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Lappy.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
